markdown: rdiscount
highlighter: rouge
permalink: /posts/:title.html
exclude:
  - README.md

name: 昌里大金猪的空间
host: nomospace.github.io

custom:
    category:
        node: node
        javascript: javascript
        css: css
        html5: html5
        frontend: frontend
    categories:
      - name: javascript
        title: javascript
      - name: node
        title: node
      - name: css
        title: css
      - name: html5
        title: html5
      - name: frontend
        title: frontend

meta:
    authors:
      - name: nomospace
        email: jinlu_hz@163.com
        gravatar: d6e8639fcaea0c7c0fab106033f05de0

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=80
